title: David Bindel
email: bindel@cornell.edu
description: CS 6210 home page
baseurl: "/courses/CS6210/2022fa/"
url: "http://www.cs.cornell.edu/"

encoding: utf-8
timezone: America/New_York

exclude: ["Rakefile"]

markdown: kramdown
